import{a as y,S as b,i as n}from"./assets/vendor-BK_rxH-O.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const L="51902075-56e09341b6a8d3328bcbea73a",w="https://pixabay.com/api/",S=15;async function v(s,o){const t={key:L,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:S,page:o};return(await y.get(w,{params:t})).data}const m=document.querySelector(".gallery"),p=document.querySelector(".loader"),h=document.querySelector(".load-more"),P=new b(".gallery a",{captionsData:"alt",captionDelay:250});function R(s){const o=s.map(t=>`
      <li class="gallery-item">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${t.likes}</p>
          <p><b>Views:</b> ${t.views}</p>
          <p><b>Comments:</b> ${t.comments}</p>
          <p><b>Downloads:</b> ${t.downloads}</p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",o),P.refresh()}function q(){m.innerHTML=""}function E(){p.classList.remove("hidden")}function $(){p.classList.add("hidden")}function B(){h.classList.remove("hidden")}function u(){h.classList.add("hidden")}const l=document.querySelector(".form"),M=document.querySelector(".load-more");let f="",a=1,d=0;l.addEventListener("submit",async s=>{if(s.preventDefault(),f=l.elements["search-text"].value.trim(),l.reset(),a=1,q(),u(),!f){n.warning({title:"Warning",message:"Please enter a search term",position:"topRight"});return}await g()});M.addEventListener("click",async()=>{a+=1,await g(!0)});async function g(s=!1){E();try{const o=await v(f,a);if(d=o.totalHits,o.hits.length===0){n.info({title:"No results",message:"Sorry, no images match your search. Please try again!",position:"topRight"}),u();return}R(o.hits),a===1&&n.success({title:"Success",message:`Found ${d} images.`,position:"topRight"});const t=Math.ceil(d/15);a<t?B():(u(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),s&&x()}catch{n.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}finally{$()}}function x(){const{height:s}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
